### ISSUE TITLE
Ontwerp tablet App

### ISSUE THREAD

**Issue by MLoth** [MLoth/Evaluest#1]
Nog geen ontwerp voor de iPad app. Enkel een (beperkte) mockup...

**Comment by MLoth** [comment]
Als we de app (Balsamiq bv) uitwerken is het ook al oke, beheersapp is zo goed als af.

**Comment by RubenVanmaelsaeke** [comment]
Is goed, beheersapp afwerken en balsamiq wireframe maken voor app, Deze week kunnen we puur focussen op deze 2 punten

**Comment by RubenVanmaelsaeke** [comment]
En design voor app dan ook, deze week moet enkel design getoond worden aan docenten (kevin en karel kunnen wel al beginnen aan functionaliteiten van de beheerssite

**Comment by MLoth** [comment]
Mijn Balsamiq trail is wel verlopen denk ik. Dus dat is wel een probleempje...

**Comment by RubenVanmaelsaeke** [comment]
Idem, andere software of opnieuw proberen installeren zijn de opties

**Comment by RubenVanmaelsaeke** [comment]
Herinstalleren lukt niet, blijft ongeregistreerd

**Comment by RubenVanmaelsaeke** [comment]
Ik heb een mail gestuurd naar joost, mss kunnen we zo aan een licentiecode geraken
