### ISSUE TITLE
Pitch Week1

### ISSUE THREAD

**Issue by KevinVanLancker** [MLoth/Evaluest#10]
Na de bespreking met Ann deze avond had ik lichtjes het gevoel dat we nog niet echt 100% onze pitch konden verdedigen.

Misschien een idee om morgen alles voor de pitch te overlopen, eventuele dingen bespreken waar we in het begin niet over nagedacht hadden, de scope volledig uitzetten en er niet meer van afwijken en dergelijke.

We hebben toch maar een halve dag en als dit goed is, kunnen we nog zo gemakkelijk verder werken aan de rest.

**Comment by KarelVerhulst** [comment]
Klinkt zeer goed voor mij ze

**Comment by MLoth** [comment]
Ja idem. We zouden inderdaad nog wat dieper moeten ingaan op de aangekaarte items.

**Comment by RubenVanmaelsaeke** [comment]
Project Scope moet herzien worden, Wireframes en Concept zijn waterdicht

**Comment by RubenVanmaelsaeke** [comment]
Functionele Analyse staat op GitHub
Requirements Analyse staat op Github
