### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by MLoth** [MLoth/Evaluest#11]
# Scope
### Compatibiliteit
De mobile app is enkel beschikbaar op moderne webbrowsers. Zoals onder andere Chrome, IE, Safari.

### Studierichtingen
We richten ons enkel op de lerarenopleiding.

**Comment by RubenVanmaelsaeke** [comment]
IE... modern

**Comment by RubenVanmaelsaeke** [comment]
Qua functionaliteiten moeten we ook een afbakening hebben
