### ISSUE TITLE
Vragen Aurélie

### ISSUE THREAD

**Issue by RubenVanmaelsaeke** [MLoth/Evaluest#13]

**Comment by RubenVanmaelsaeke** [comment]
Link naar huidige database om deliberatiescherm te kunnen oproepen?

**Comment by RubenVanmaelsaeke** [comment]
Hoe archivering voorzien? Voor hoeveel jaar moeten deze formulieren bijgehouden worden, hoe zit dit momenteel?

**Comment by RubenVanmaelsaeke** [comment]
Wat is concreet de scope van het project, enkel de overstap van papier naar een mobiele app oplossing? Of wilt de opleiding eigenlijk meer dan dit?

**Comment by KevinVanLancker** [comment]
Wie beheert de formulieren en hoe kan deze persoon momenteel de formulieren bewerken?

**Comment by RubenVanmaelsaeke** [comment]
Link naar deliberatiescherm => Niet nodig (Data komt toch op SharePoint te staan)
Archivering => momenteel wordt niks bijgehouden, is dus niet nodig
Scope => We beperken ons tot de Mobile App, Beheer App is al bestaand in SharePoint zelf
Formulieren => worden bewerkt op SharePoint wanneer nodig, staan op SharePoint, bewerkt via SharePoint

We kunnen verder met het project met wat we nu weten
