### ISSUE TITLE
Testomgeving Sharepoint

### ISSUE THREAD

**Issue by MLoth** [MLoth/Evaluest#14]
Lijst ophalen in sharepoint 2010 & 2013 met php. Zie testlijst.

**Comment by RubenVanmaelsaeke** [comment]
Stages 2014 - 2015

https://start.howest.be/Onderwijs/Opleidingen/KleuterEnLagerOnderwijs/volgsys/Lists/Stages%2020142015/stagelijst.aspx

Volglijst:

https://start.howest.be/Onderwijs/Opleidingen/KleuterEnLagerOnderwijs/volgsys/Lists/volgsysteem%20stage%20XL/stagelijst.aspx

**Comment by MLoth** [comment]
Lijsten op eigen Sharepoint zetten. Dan kunnen we deze data ophalen alsof het de eigenlijk data is.

**Comment by RubenVanmaelsaeke** [comment]
We gebruiken SharePoint lijsten (temporary lijsten van excel) om ons prototype op te bouwen

**Comment by RubenVanmaelsaeke** [comment]
Lijsten werden al op SharePoint gezet, wordt gesloten. (De data ophalen wordt een taak van iemand anders)
