### ISSUE TITLE
Week 2 Planning

### ISSUE THREAD

**Issue by RubenVanmaelsaeke** [MLoth/Evaluest#18]
- [ ] Karel: Een manier zoeken om SharePoint data op te halen uit de lijsten op Karel's account om zo te kunnen gebruiken in onze Mobile App om een prototype te bouwen. (Deadline: Dinsdag 4/06)
- [x] Kevin: Website offline beschikbaar maken en gegevens opslaan ( prototype) (Deadline: Dinsdag 2/06)
- [x] Ruben: Functionele Analyse en Technische Analyse van het Project, in aanloop naar Pitch Week 2. Work Breakdown Structure opbouwen gebruikmakend van de planning en werkpakketten. (Deadline: Donderdag 4/06)
- [x] Martijn: HTML CSS van de Mobile App verder uitwerken, bouwen op de schermen van de Wireframes (Zie GitHub). Layout en Design moet af zijn, dit is de definitieve versie waaraan je werkt. (Bouw alvast een basis voor het inladen van het formulier, zorg dat dynamisch de data correct ingeladen en geplaatst kan worden, later nog uitwerken met Javascript) (Deadline: Dinsdag 2/06)

**Comment by KevinVanLancker** [comment]
De manieren die we tot nu toe al hebben gezien maken gebruik van de login.
Bijhouden zal gwn een kwestie van cookies zijn lijkt me, wat ik wel een probleem in vindt is het filteren per docent.
In het excel bestandje staat de naam van de docent, maar de gebruiker is op SP bekend onder zijn inlognaam ( aka mailadres).
Maar, ik zal dat alleszins morgen nog eens bestuderen

**Comment by MLoth** [comment]
Klinkt erg agile...

**Comment by KarelVerhulst** [comment]
we gaan keer ons best doen eh !!!!

**Comment by RubenVanmaelsaeke** [comment]
@Kevin: Klinkt zeker goed, we zien wel wat het beste lijkt te zijn.
@Karel: That's the spirit !!!! ;-)

**Comment by RubenVanmaelsaeke** [comment]
Klinkt goed!

**Comment by KevinVanLancker** [comment]
Heb gekeken voor die gegevens van SP.
Iedere gebruiker heeft op zijn profiel normaal zijn naam staan ( in mijn geval Van Lancker Kevin). Dit zou redelijk simpel moeten zijn om af te halen eenmaal de login werkt. Dus ik stel voor dat ik Karel nu laat werken om die data van SP af te halen, eenmaal dat werkt kan ik dan omzetten naar een algemeen iets.

Tot dan zal ik mij al bezighouden om de website offline beschikbaar te maken.

**Comment by RubenVanmaelsaeke** [comment]
Planning zal op een andere manier uitgevoerd worden vanaf nu, dit wordt gesloten.
