### ISSUE TITLE
Evaluatieformulier later nog kunnen bewerken

### ISSUE THREAD

**Issue by RubenVanmaelsaeke** [MLoth/Evaluest#19]
Scenario: Docent vult formulier van een student in, drukt op opslaan om dit later nog te kunnen bewerken. Dit wordt ergens opgeslagen (Manifest?) zodat we dit later kunnen oproepen om nog te bewerken voor de Docent doorstuurt naar SharePoint.
Enkele opties:
- Extra Scherm na login waar gebruiker keuze heeft om nieuwe evaluatie te maken of bestaande evaluaties (nog niet doorgestuurd) nog te bewerken.
- Zoals Martijn zei, in de dropdown van studenten de naam van de student hernoemen naar: <student> - CONCEPT en zo het reeds opgeslagen opject nog kunnen bewerken.

Ik vind persoonlijk dat een extra scherm gebruiksvriendelijker is aangezien dit duidelijk wordt getoond (UX) ipv subtiel ergens CONCEPT bij te plaasten, zal niet duidelijk zijn voor enkele gebruikers...

**Comment by MLoth** [comment]
We kunnen kijken om een label te voorzien in de app. Voor mij niet een enorm dringend zaak, eerder een 'verbetering' (doch noodzakelijk).

**Comment by RubenVanmaelsaeke** [comment]
Ik zal dit aan jou als taak dan toewijzen, het feit dat we het als concept (label toevoegen) opslaan werd als reeds beslist. Wordt gesloten.
