### ISSUE TITLE
Planning aanhouden

### ISSUE THREAD

**Issue by MLoth** [MLoth/Evaluest#2]
Volgens onze planning moeten we op het begin van de projectweken het volledige ontwerp af hebben. Voorlopig zijn we daar nog niet aan toe gekomen, misschien kunnen we hier eens over communiceren...

**Comment by KarelVerhulst** [comment]
da s een goe idee
maar hadden we nie al iets op papier van ontwerp??

**Comment by MLoth** [comment]
Ja, maar er was sprake van het afwerken van de frontend... Das net ietsje meer.

**Comment by RubenVanmaelsaeke** [comment]
Niet vergeten dat de projectweken startne in juni... examens eindigen op 22 mei. Frontend kan gemaakt worden ervoor, zie ik geen probleem vormen

**Comment by MLoth** [comment]
Oke. Dan is het ook goed. Die periode lijkt me ook wel voldoende.
Op 3 mei 2015 14:07 schreef "Ruben" <notifications@github.com>:
