### ISSUE TITLE
Martijn: Formulieren versie verschilt van SharePoint -> Geen internet, Hoe oplossen?

### ISSUE THREAD

**Issue by MLoth** [MLoth/Evaluest#21]
- een ingeladen student wordt niet geëvalueerd, wat nu?
  - telkens niet geevalueerde studenten 'opnieuw' inladen -> solved
- afmelden
  - toevoegen aan de app
- vergeten om op voorhand aan te melden, volledig manueel invullen?

**Comment by RubenVanmaelsaeke** [comment]
Eens een docent is aangemeld wordt de data van stagiairs ingeladen EN de formulieren dus ga ik even het flow diagram moeten aanpassen trouwens.

Als een docent vergeet om vooraf aan te melden -> kijken of de token er nog is en de formulieren zijn nog steeds ingeladen (van een vorige login). Nu is de docent nog steeds aangemeld (adhv token) en kan de docent manueel de stagegegevens invullen en wordt het formulier aldus correct ingeladen. Eens er terug internet verbinding is en de status van het evaluatie object werd op "versturen" gezet zal het naar SharePoint worden verstuurd met de zelf ingevulde waarden.

Stel dat de docent aangemeld is wegens de token, dus niet vooraf heeft aangemeld en deze verplaatst zich naar een school zonder internet en het blijkt dat de versie van de fomulieren outdated is, de formulieren zijn aangepast op SharePoint en moeten opnieuw opgehaald worden, maar daar is geen internet voor. Hoe lossen we dit op? 
(FitGap!)

**Comment by RubenVanmaelsaeke** [comment]
Werd in de FitGap analyse opgenomen, dit is een long term issue. Wordt gesloten.
