### ISSUE TITLE
Orde en netheid...

### ISSUE THREAD

**Issue by MLoth** [MLoth/Evaluest#22]
Momenteel zijn er de volgende issues: Sharepoint, Sharepoint issues en Sharepoint connection... Dat is niet echt handig... Kijk even om dingen samen te houden.

**Comment by RubenVanmaelsaeke** [comment]
Wordt inderdaad gedaan. Nieuwe structuur wordt toegepast, zie labels met namen teamleden. Vanaf nu geen issues met 20 verschillende zaken in!
