### ISSUE TITLE
Connectie met SharePoint mbv PHP

### ISSUE THREAD

**Issue by RubenVanmaelsaeke** [MLoth/Evaluest#26]
Connecteren en Data ophalen mbv PHP

**Comment by MLoth** [comment]
1. Eigenlijke verbinding moet met ADFS (https://github.com/schakra/Active-Directory-Sample-for-PHP-Developers)
2. Mogelijk zijn er extra handelingen nodig op de server om de nodige permissies te krijgen...
3. SharePoint zet 30 cookies (!), het zetten van de cookie die bij houdt of je

**Comment by KevinVanLancker** [comment]
Ik ga hier nu ook aan werken, dit is momenteel 1 van de belangrijkere issues.
Zonder dit staan we nergens

**Comment by RubenVanmaelsaeke** [comment]
Is heel goed, ik zal het opnemen in de planningen en grafieken
