### ISSUE TITLE
App moet offline gebruikt kunnen worden

### ISSUE THREAD

**Issue by RubenVanmaelsaeke** [MLoth/Evaluest#28]
In de App moet offline data kunnen gecommuniceerd worden. Dit doe je goed, ik zie dat je heel wat aan het testen bent.

**Comment by KevinVanLancker** [comment]
momenteel bezig met dit prototype:

Gebruiker meldt zich aan ( gwn uw mailadres)
Aan de hand van uw mailadres wordt een lijst van studenten opgehaald.
Zorgen dat de lijst blijft getoond worden wanneer je offline gaat.

Extras afhankelijk van tijd:
Student verwijderen van de lijst in offline-mode en zorgen dat deze wordt verwijdert op de DB als je online bent

**Comment by RubenVanmaelsaeke** [comment]
Klinkt goed.

**Comment by KevinVanLancker** [comment]
Mijn php kennis zat toch wat verder dan ik dacht ( en ook paar idiote fouten gemaakt).
Dus er zit ietwat vertraging op.

Momenteel heb ik deze functionaliteit:
Als je je inlogt et je mailadres zal je alle studenten zien die je moet evalueren.

Vandaag en morgen zorg ik ervoor dat je deze studenten ook offline kan zien en zal ik waarschijnlijk ook ervoor kunnen zorgen dat je studenten kan weghalen offline en wanneer je offline komt ze ook van database gaan.

Om voorlopig eens te testen gebruik je je howest email, iedereen van onze groep heeft zen eigen studenten

**Comment by RubenVanmaelsaeke** [comment]
Prima, klinkt goed, met jouw deel hebben we iets van demo die we kunnen tonen mochten ze een soort van prototype vragen.

**Comment by KarelVerhulst** [comment]
http://evaluest.howest.be/Prototype/

kevin was dit nog vergeten

**Comment by RubenVanmaelsaeke** [comment]
Fantastisch Karel, bedankt!

**Comment by KevinVanLancker** [comment]
heb hier wat meegewerkt, probleem is wel, de items die nodig zijn om het offline te zetten, blijven zo, ookal kom je terug online
VB:. ik laad mijn lijst van studenten op voor de eerste keer.
Ik voeg in de database een nieuwe student toe.
Deze nieuwe student wordt niet toegevoegd, alle studenten die ik reeds had blijven er staan.

Met de offline/offline demos kan dit verandert worden omdat men de gegevens niet vanuit een database ophaalt en daarna pas in de indexeddb steekt.

Heb hier redelijk wat tijd ingestoken en ik geraak niet meer verder, dus ik denk dat het het beste is dat ik nu iets anders doe en dan kunnen we later met meerdere personen kijken naar het offline gedeelte.
