### ISSUE TITLE
Connectie sharepoint

### ISSUE THREAD

**Issue by MLoth** [MLoth/Evaluest#3]
Connectie maken met sharepoint. Dit houdt in dat er aangemeld kan worden en dat er data opgehaald kan worden (samen met andere CRUD operaties).

**Comment by RubenVanmaelsaeke** [comment]
Een account met redelijk wat toegang permissies zal vereist zijn

**Comment by MLoth** [comment]
Dit lukt nog niet met onze php site...

**Comment by RubenVanmaelsaeke** [comment]
Dit is niet meer van toepassing, wordt gesloten.
