### ISSUE TITLE
Docent moet kunnen afmelden op de App

### ISSUE THREAD

**Issue by RubenVanmaelsaeke** [MLoth/Evaluest#31]
Gelieve een actie om te kunnen afmelden op de App implementeren. In het vervolg ook graag de recentste versie op GitHub plaatsen. Dit is hoe we werken, hier niet van afwijken.

**Comment by MLoth** [comment]
Klinkt niet echt agile...

**Comment by RubenVanmaelsaeke** [comment]
Waarom is dit niet Agile? Ik wordt als scrummaster aangeduid en maak een planning op, zoals van mij gevraagd werd. 

Iedereen werkt alsook op GitHub, tot we leerden dat we niks aan Frontend kunne doen omdat de recentste versie niet beschikbaar is.

**Comment by RubenVanmaelsaeke** [comment]
Functionaliteit werd toegevoegd aan Frontend (implementatie van backend komt eraan eens we kunnen inloggen -> ander werkpakket)
