### ISSUE TITLE
Hard Coded Javascript Prototype van een Formulier (voor klant)

### ISSUE THREAD

**Issue by RubenVanmaelsaeke** [MLoth/Evaluest#33]

**Comment by RubenVanmaelsaeke** [comment]
Het prototype qua frontend is af, nu gaan we de offline vooruitgang van Kevin implementeren in de App om zo onze functionaliteiten te kunnen tonen aan de klant in de volgende Meeting. Kevin, ik heb je toegevoegd aan dit werkpakket, hieraan werk je samen met Martijn.

**Comment by MLoth** [comment]
Is al redelijk goed in orde, maar zeker nog niet af (compatibiliteit #38 ). Morgen (4/6) eens kijken voor het offline bij houden van een resem student objecten. Later eventueel een formulier tonen adhv de geselecteerde input, maar dat hoeft mijns inziens niet per se voor de eerste test van de user.

**Comment by RubenVanmaelsaeke** [comment]
Ja voor de klant is dit zeker genoeg, voor docenten ben ik niet zeker

**Comment by RubenVanmaelsaeke** [comment]
Basis van het prototype is af, verder compatibiliteit zijn andere werkpakketten, offline implementatie komt later aan bod, eens we authenticeren (karel & kevin)
