### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by MLoth** [MLoth/Evaluest#4]
## Heikele punten server
1. Enkel toegang tot server via schoolnetwerk
2. (Volgens mij) Geen geëncrypteerde verbinding - https://konklone.com/post/switch-to-https-now-for-free
3. Pro tip was om dingen te up- en downloaden naar eigen server i.p.v. direct naar sharepoint. Dus moet er een soort queue zijn op onze server.

**Comment by MLoth** [comment]
Maar dit is denk ik meer iets voor onze scrummaster Karel :trollface: !

**Comment by RubenVanmaelsaeke** [comment]
:p

**Comment by RubenVanmaelsaeke** [comment]
Eens contact opnemen met helpdesk en vragen of ze ons hiermee verder kunnen helpen...

**Comment by KarelVerhulst** [comment]
kevin en ik zullen kijken voor die mail naar de helpdesk te sturen

**Comment by KevinVanLancker** [comment]
Mail is verstuurd naar de helpdesk. Ik heb in de cc Ann en Kevin gezet, wie weet hebben zij ook nog wat informatie hieromtrent ( Kevin met het algemene gedeelte, Ann met sharepoint)

**Comment by RubenVanmaelsaeke** [comment]
Prima!

**Comment by RubenVanmaelsaeke** [comment]
- Encryptie op Mobile App => Certificaat? HTTPS?
- Server (Evaluest) moet beschikbaar zijn buiten schoolnetwerk

Vragen voor Bart Strubbe... of individueel opzoeken Karel en Kevin :)

**Comment by RubenVanmaelsaeke** [comment]
Werd ofwel opgelost of in een andere issues gebruikt. Wordt gesloten.
