### ISSUE TITLE
Gitub gebruik

### ISSUE THREAD

**Issue by MLoth** [MLoth/Evaluest#6]
Enkele reminders:
##### Eerst synchen, dan commit
Dit kan conflicten voorkomen. En het is een kleine moeite :smile:.

##### Openbaar
Alles wat hier op Github staat is (hopelijk voorlopig) openbaar, hou daar ook rekening mee.

**Comment by RubenVanmaelsaeke** [comment]
Iedereen (docenten!) kunnen meekijken...

**Comment by KevinVanLancker** [comment]
Dus als ik wil werken, eerst synchen, dan eraan werken, dan terug synchen en dan committen?
