### ISSUE TITLE
Sharepoint Issues

### ISSUE THREAD

**Issue by RubenVanmaelsaeke** [MLoth/Evaluest#7]
Enumeration of Sharepoint issues and question...

**Comment by RubenVanmaelsaeke** [comment]
Afmetingen Profile Pictures van studenten voor de Evaluest App (FRONTEND)

**Comment by RubenVanmaelsaeke** [comment]
Hoe worden gegevens naar Sharepoint ingegeven (Formulier, Data, enz.)

**Comment by RubenVanmaelsaeke** [comment]
Afbeeldingen (Profile Pictures) studenten => Portrait of Landscape?

**Comment by KarelVerhulst** [comment]
https://spsawyer.wordpress.com/2013/07/31/sharepoint-2013-user-profile-photo-sizes/

**Comment by RubenVanmaelsaeke** [comment]
Ik bedoel meer hoe afbeeldingen worden geupload naar Sharepoint (Dus specifiek de studenten van Howest Brugge Leerkrachten Opleiding) Misschien contact opnemen met de opdrachtgever karel voor een voorbeeld, eventueel vragen of we met haar account even Sharepoint kunnen bestuderen

**Comment by KevinVanLancker** [comment]
dit staat in men mail naar de helpdesk:

"Voor ons project moeten wij zorgen dat docenten zich kunnen aanmelden op sharepoint en hun beoordeling van de stage die ze hebben bezocht automatisch wordt geupload. Uiteraard kunnen wij als studenten dit niet testen en vroegen ons af of de HoWest geen testomgeving heeft om dit alsnog te kunnen testen."

behulpzaam genoeg?

**Comment by RubenVanmaelsaeke** [comment]
Is in orde, best is communicatie met coach, zoals we in onze heel summiere scrum meeting hebben vastgesteld ;)

**Comment by RubenVanmaelsaeke** [comment]
http://app.howest.be/bamaflex/studentfoto.aspx/studentfoto.aspx?id=23886

Voorbeeld van een profile picture URL (API? apparently)

**Comment by RubenVanmaelsaeke** [comment]
- Profile Pictures varieren, maar met HTML CSS wordt dit geen probleem
- Formulier data zijn puur SharePoint lijsten => inlezen via PHP? misschien, we werken hieraan
